"""add_temporal_auditor_columns

Revision ID: 2757e65bb83a
Revises: fa22b7a4dba5
Create Date: 2026-09-09 23:34:13.637387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2757e65bb83a'
down_revision: Union[str, Sequence[str], None] = 'fa22b7a4dba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memolets', sa.Column('is_time_sensitive', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('memolets', sa.Column('deprecation_risk', sa.String(), server_default='none', nullable=True))
    op.add_column('memolets', sa.Column('temporal_anchor', sa.String(), nullable=True))
    op.add_column('memolets', sa.Column('validity_horizon_days', sa.Integer(), server_default='365', nullable=True))
    op.add_column('memolets', sa.Column('is_deprecated', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('memolets', sa.Column('deprecation_reason', sa.String(), nullable=True))
    op.add_column('memolets', sa.Column('suggested_update', sa.String(), nullable=True))
    op.add_column('memolets', sa.Column('audited_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_memolets_user_id'), 'memolets', ['user_id'], unique=False)
    op.drop_constraint(op.f('memolets_conversation_id_fkey'), 'memolets', type_='foreignkey')
    op.create_foreign_key(None, 'memolets', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'memolets', type_='foreignkey')
    op.create_foreign_key(op.f('memolets_conversation_id_fkey'), 'memolets', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_memolets_user_id'), table_name='memolets')
    op.drop_column('memolets', 'audited_at')
    op.drop_column('memolets', 'suggested_update')
    op.drop_column('memolets', 'deprecation_reason')
    op.drop_column('memolets', 'is_deprecated')
    op.drop_column('memolets', 'validity_horizon_days')
    op.drop_column('memolets', 'temporal_anchor')
    op.drop_column('memolets', 'deprecation_risk')
    op.drop_column('memolets', 'is_time_sensitive')
    # ### end Alembic commands ###
